version: '3.8'

services:
 backend:
  image: backend2 #I have the image locally
  ports:
  - 8080:8080
  container_name: backend

 frontend:
  image: front2 #I have the image locally
  ports:
  - 5000:5000
  container_name: frontend

 redis:
  image: redis
  container_name: redis
  expose:
    - 6379
